### ISSUE TITLE
olivia_olivia-ai.org_1 exited with code 1

### ISSUE THREAD

**Issue by newtonsart** [olivia-ai/olivia#119]
``` lolart@lolarch  ~/shit/olivia   master  docker-compose up 
Starting olivia_olivia-ai.org_1 ... done
Starting olivia_olivia_1        ... done
Attaching to olivia_olivia-ai.org_1, olivia_olivia_1
olivia-ai.org_1  | net.js:1490
olivia-ai.org_1  |   throw new ERR_INVALID_OPT_VALUE('options', inspect(options));
olivia-ai.org_1  |   ^
olivia-ai.org_1  | 
olivia-ai.org_1  | TypeError [ERR_INVALID_OPT_VALUE]: The value "{ port: true, host: '0.0.0.0' }" is invalid for option "options"
olivia-ai.org_1  |     at Server.listen (net.js:1490:9)
olivia-ai.org_1  |     at HttpServer.listen (/usr/local/lib/node_modules/http-server/lib/http-server.js:205:22)
olivia-ai.org_1  |     at listen (/usr/local/lib/node_modules/http-server/bin/http-server:163:10)
olivia-ai.org_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/http-server/bin/http-server:113:3)
olivia-ai.org_1  |     at Module._compile (internal/modules/cjs/loader.js:1133:30)
olivia-ai.org_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
olivia-ai.org_1  |     at Module.load (internal/modules/cjs/loader.js:977:32)
olivia-ai.org_1  |     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
olivia-ai.org_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
olivia-ai.org_1  |     at internal/main/run_main_module.js:18:47 {
olivia-ai.org_1  |   code: 'ERR_INVALID_OPT_VALUE'
olivia-ai.org_1  | }
olivia_1         |        _ _       _
olivia_1         |   ___ | (_)_   _(_) __ _
olivia_1         |  / _ \| | \ \ / / |/ _` |
olivia_1         | | (_) | | |\ V /| | (_| |
olivia_1         |  \___/|_|_| \_/ |_|\__,_|
olivia_1         | 
olivia_1         | Loading the neural network from res/locales/en/training.json
olivia_1         | Loading the neural network from res/locales/de/training.json
olivia_1         | Loading the neural network from res/locales/fr/training.json
olivia_1         | Loading the neural network from res/locales/es/training.json
olivia_1         | Loading the neural network from res/locales/ca/training.json
olivia_1         | Loading the neural network from res/locales/it/training.json
olivia_1         | 
olivia_1         | Server listening on the port 8080...
olivia_olivia-ai.org_1 exited with code 1```
Im using Archlinux

**Comment by hugolgst** [comment]
I am going to investigate that, thanks for reporting.

**Comment by hugolgst** [comment]
The issue has been fixed, please execute `docker-compose pull` to get the updates.
