### ISSUE TITLE
I should have some questions.

### ISSUE THREAD

**Issue by xzyan** [olivia-ai/olivia#53]
```log
Loading the neural network from res/training.json

Listening on the port 8080...
2019/07/05 08:07:47 http: panic serving 127.0.0.1:40922: runtime error: invalid memory address or nil pointer dereference
goroutine 51 [running]:
net/http.(*conn).serve.func1(0xc0000bc280)
	/usr/local/dev/go/src/net/http/server.go:1769 +0x139
panic(0x737600, 0xa483d0)
	/usr/local/dev/go/src/runtime/panic.go:522 +0x1b5
github.com/gorilla/websocket.(*Conn).NextReader(0x0, 0xc0006680a4, 0x1, 0x80c260, 0x7b1b70, 0x79968d)
	/home/master/olivia/src/github.com/gorilla/websocket/conn.go:936 +0x26
github.com/gorilla/websocket.(*Conn).ReadMessage(0x0, 0x811660, 0xc0001142a0, 0xc0004aa000, 0x0, 0x0, 0x80c0c0)
	/home/master/olivia/src/github.com/gorilla/websocket/conn.go:1026 +0x2f
main.Handle(0x811660, 0xc0001142a0, 0xc0004aa000)
	/home/master/olivia/main.go:64 +0x89
net/http.HandlerFunc.ServeHTTP(0x7b1b70, 0x811660, 0xc0001142a0, 0xc0004aa000)
	/usr/local/dev/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xa55720, 0x811660, 0xc0001142a0, 0xc0004aa000)
	/usr/local/dev/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00009e410, 0x811660, 0xc0001142a0, 0xc0004aa000)
	/usr/local/dev/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0000bc280, 0x811ce0, 0xc000026100)
	/usr/local/dev/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/dev/go/src/net/http/server.go:2884 +0x2f4
2019/07/05 08:07:47 http: panic serving 127.0.0.1:40924: runtime error: invalid memory address or nil pointer dereference
goroutine 52 [running]:
net/http.(*conn).serve.func1(0xc0000bc320)
	/usr/local/dev/go/src/net/http/server.go:1769 +0x139
panic(0x737600, 0xa483d0)
	/usr/local/dev/go/src/runtime/panic.go:522 +0x1b5
github.com/gorilla/websocket.(*Conn).NextReader(0x0, 0xc000288924, 0xc, 0x80c260, 0x7b1b70, 0x79968d)
	/home/master/olivia/src/github.com/gorilla/websocket/conn.go:936 +0x26
github.com/gorilla/websocket.(*Conn).ReadMessage(0x0, 0x811660, 0xc000114380, 0xc0004aa100, 0x0, 0x0, 0x80c0c0)
	/home/master/olivia/src/github.com/gorilla/websocket/conn.go:1026 +0x2f
main.Handle(0x811660, 0xc000114380, 0xc0004aa100)
	/home/master/olivia/main.go:64 +0x89
net/http.HandlerFunc.ServeHTTP(0x7b1b70, 0x811660, 0xc000114380, 0xc0004aa100)
	/usr/local/dev/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xa55720, 0x811660, 0xc000114380, 0xc0004aa100)
	/usr/local/dev/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00009e410, 0x811660, 0xc000114380, 0xc0004aa100)
	/usr/local/dev/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0000bc320, 0x811ce0, 0xc000026380)
	/usr/local/dev/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/dev/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by ananagame** [comment]
Did you changed somerthing?
