### ISSUE TITLE
Model Training not working

### ISSUE THREAD

**Issue by adorearun** [olivia-ai/olivia#54]
I have added like 25 new intents in res/intents.json. I removed training.json and restarted the server. Out of 25 only 3 or 4 is working rest I am getting 
```{"content":"I'm trying to do my best but I don't understand","tag":"don't understand"}```

What could be the reason? How to train the model with our new intents? Do we have to remove training.json if we add new intents ?

**Comment by ananagame** [comment]
You need to add your intents in `res/intents.json` written following this pattern ```json
{
    "tag": "your tag",
    "patterns": ["Hey", "Hello", "Hi", "Good morning"],
    "responses": ["hello how are you"],
    "context": ""
}
```

Then delete the training save in `res/training.json` and restart the server, you should see a progress bar.
If you meet other problems, send me some of the intents that are not working. :)

**Comment by adorearun** [comment]
~~~    {
        "tag": "submittedprocessed",
        "patterns": ["difference between submitted and processed requests"],
        "responses": ["refer this link <link to the page>."],
        "context": ""
      }~~~

I tried but sometimes it works and sometimes it fails. Not sure how to debug it.

**Comment by ananagame** [comment]
And what do you try to send to Olivia to trigger this intent?

**Comment by adorearun** [comment]
I am sending the entire pattern ```difference between submitted and processed requests``` and trigger using rest API

**Comment by adorearun** [comment]
Moreover after I deploy the olivia in our private cloud server , now even for existing models its failing. what could be the reason? please help.

```
  [OUT] "are you an ai"
▫︎ men - 0.2391154659211019
▫︎ rtd records - 0.2158050943699062
▫︎ identity - 0.21338464524881018
▫︎ women - 0.12923002845499962
▫︎ feeling - 0.06610500074858752
▫︎ age - 0.057829643696481525
▫︎ action - 0.05651120291794197

-------------------------------------
 "hi"
  ▫︎ men - 0.15529056941073868
  ▫︎ rtd records - 0.0975703835293949
  ▫︎ disasterreport - 0.07539111951442716
  ▫︎ ebusiness - 0.07123962433210258
  ▫︎ math - 0.06957340052798311
  ▫︎ women - 0.055229851356285845
  ▫︎ age - 0.05075387785014926
  

```

**Comment by ananagame** [comment]
Yes I know this I am actually working on it

**Comment by ananagame** [comment]
I tested your intent myself and it's working perfectly ![see here](https://i.imgur.com/w8KjiCU.png)
Maybe this is due to the last fixes I've done on the neural network

**Comment by adorearun** [comment]
Oh cool , Thanks. Do I have to update to latest version?

**Comment by ananagame** [comment]
Sure. :)

**Comment by adorearun** [comment]
After I updated to latest master branch and when I try to access olivia end up in this error , please help

`2019/07/25 16:43:14 http: panic serving [::1]:62633: runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc0000a21e0)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1769 +0x139
panic(0x1352ec0, 0x16814d0)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
github.com/olivia-ai/olivia/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0x0, 0x0, 0xc000053c80, 0x1260bf9, 0x168e2c0, 0xc0001637c0)
	/Users/AXP1397/go/src/github.com/olivia-ai/olivia/vendor/github.com/gorilla/websocket/conn.go:938 +0x26
github.com/olivia-ai/olivia/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage(0x0, 0x14324c0, 0xc00050c0e0, 0xc000124000, 0x0, 0x0, 0x142cd00)
	/Users/AXP1397/go/src/github.com/olivia-ai/olivia/vendor/github.com/gorilla/websocket/conn.go:1028 +0x2f
main.Handle(0x14324c0, 0xc00050c0e0, 0xc000124000)
	/Users/AXP1397/go/src/github.com/olivia-ai/olivia/main.go:67 +0x8f
net/http.HandlerFunc.ServeHTTP(0x13cf7a0, 0x14324c0, 0xc00050c0e0, 0xc000124000)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x168e2c0, 0x14324c0, 0xc00050c0e0, 0xc000124000)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00008a4e0, 0x14324c0, 0xc00050c0e0, 0xc000124000)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0000a21e0, 0x1432c80, 0xc000170200)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2884 +0x2f4`

**Comment by ananagame** [comment]
Did you reproduce all the steps?

**Comment by adorearun** [comment]
Yes , I pulled master and did dep ensure and end up this problem? Can you please let me know what could be the issue ?

**Comment by adorearun** [comment]
Hi , Is there something I am missing ? or did you get a chance to look into it?

**Comment by ananagame** [comment]
I really don't know this is working perfectly for me, sorry :/
